[package]
name = "fs_wasm"
version = "0.4.14"
authors = ["ugnic <ryuto.nishida@meetasu.jp>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/ugnic/fs_wasm"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
crc32fast = "1.0"
rand = "0.7"
chrono = "0.4"